=== rnavagamuwa/SwaggerJsonMerger/modules/swagger-compat-spec-parser/src/main/resources/schemas/v1.1/apiDeclaration.json
{
  "id": "http://swagger-api.github.io/schemas/v1.1/apiDeclaration.json#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "swaggerVersion",
    "basePath",
    "apis"
  ],
  "properties": {
    "swaggerVersion": {
      "enum": [
        "1.1"
      ]
    },
    "apiVersion": {
      "type": "string"
    },
    "basePath": {
      "type": "string",
      "format": "uri",
      "pattern": "^https?://"
    },
    "resourcePath": {
      "type": "string",
      "format": "uri"
    },
    "apis": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/apiObject"
      }
    },
    "models": {
      "type": "object",
      "additionalProperties": {
        "$ref": "modelsObject.json#"
      }
    }
  },
  "additionalProperties": false,
  "definitions": {
    "apiObject": {
      "type": "object",
      "required": [
        "path",
        "operations"
      ],
      "properties": {
        "path": {
          "type": "string",
          "format": "uri-template"
        },
        "description": {
          "type": "string"
        },
        "operations": {
          "type": "array",
          "items": {
            "$ref": "operationObject.json#"
          }
        }
      },
      "additionalProperties": false
    }
  }
}

=== rnavagamuwa/SwaggerJsonMerger/modules/swagger-compat-spec-parser/src/main/resources/patches/t.json
{
  "apiVersion": "1.1",
  "swaggerVersion": "1.1",
  "basePath": "https://www.callfire.com/api/1.1/rest",
  "resourcePath": "/broadcast",
  "apis": [
    {
      "path": "/broadcast",
      "description": "Creates a new Broadcast",
      "operations": [
        {
          "nickname": "CreateBroadcast",
          "responseClass": "void",
          "summary": "Creates a new Broadcast",
          "notes": "<p>This operation creates a Broadcast campaign and returns a broadcastId. To see the status of this campaign call <code>GetBroadcast</code> with the returned broadcastId. </p> <p>There are 3 types of Broadcast: TEXT, IVR, or VOICE. Select the appropriate config to match the broadcast type, TextBroadcastConfig, IvrBroadcastConfig, or VoiceBroadcastConfig. Prefer the Text Service operations (ex: <code>SendText</code>) and Call Service operations (ex: <code>SendCall</code>) over this operation when managing simple text and call campaigns since those operations are simpler and more concise. </p>",
          "parameters": [
            {
              "paramType": "form",
              "name": "RequestId",
              "description": "Unique ID of web request to de-dup on",
              "$ref": "anyURI"
            },
            {
              "paramType": "form",
              "name": "Name",
              "description": "Name of Broadcast",
              "required": true,
              "type": "string"
            },
            {
              "paramType": "form",
              "name": "Type",
              "description": "Type of Broadcast",
              "allowableValues": {
                "valueType": "LIST"
              },
              "enum": [
                "VOICE",
                "IVR",
                "TEXT"
              ],
              "$ref": "BroadcastType"
            },
            {
              "paramType": "form",
              "name": "From",
              "description": "E.164 11 digit number or short code",
              "conditions": [
                {
                  "field": "Type",
                  "value": "VOICE"
                }
              ],
              "$ref": "PhoneNumber"
            },
            {
              "paramType": "form",
              "name": "LocalRestrictBegin",
              "description": "Earliest time a client can be contacted in the timezone associated with the number's NPA/NXX",
              "conditions": [
                {
                  "field": "Type",
                  "value": "VOICE"
                }
              ],
              "$ref": "time"
            },
            {
              "paramType": "form",
              "name": "LocalRestrictEnd",
              "description": "Latest time a client can be contacted in the timezone associated with the number's NPA/NXX",
              "conditions": [
                {
                  "field": "Type",
                  "value": "VOICE"
                }
              ],
              "$ref": "time"
            },
            {
              "paramType": "form",
              "name": "MaxAttempts",
              "description": "Max attempts to retry broadcast (default: 1)",
              "conditions": [
                {
                  "field": "Type",
                  "value": "VOICE"
                }
              ],
              "type": "integer",
              "format": "int32"
            },
            {
              "paramType": "form",
              "name": "MinutesBetweenAttempts",
              "description": "Minutes between broadcast attempts (default: 60)",
              "conditions": [
                {
                  "field": "Type",
                  "value": "VOICE"
                }
              ],
              "type": "integer",
              "format": "int32"
            },
            {
              "paramType": "form",
              "name": "RetryResults",
              "description": "Conditions to retry on",
              "allowableValues": {
                "valueType": "LIST"
              },
              "allowMultiple": true,
              "conditions": [
                {
                  "field": "Type",
                  "value": "VOICE"
                }
              ],
              "enum": [
                "LA",
                "AM",
                "BUSY",
                "DNC",
                "XFER",
                "XFER_LEG",
                "NO_ANS",
                "UNDIALED",
                "SENT",
                "RECEIVED",
                "DNT",
                "TOO_BIG",
                "INTERNAL_ERROR",
                "CARRIER_ERROR",
                "CARRIER_TEMP_ERROR"
              ],
              "$ref": "Result"
            },
            {
              "paramType": "form",
              "name": "RetryPhoneTypes",
              "description": "Phone types to call in retry",
              "allowableValues": {
                "valueType": "LIST"
              },
              "allowMultiple": true,
              "conditions": [
                {
                  "field": "Type",
                  "value": "VOICE"
                }
              ],
              "enum": [
                "FIRST_NUMBER",
                "HOME_PHONE",
                "WORK_PHONE",
                "MOBILE_PHONE"
              ],
              "$ref": "RetryPhoneType"
            },
            {
              "paramType": "form",
              "name": "AnsweringMachineConfig",
              "description": "Action to take if machine answers",
              "allowableValues": {
                "valueType": "LIST"
              },
              "conditions": [
                {
                  "field": "Type",
                  "value": "VOICE"
                }
              ],
              "enum": [
                "AM_ONLY",
                "AM_AND_LIVE",
                "LIVE_WITH_AMD",
                "LIVE_IMMEDIATE"
              ],
              "$ref": "AnsweringMachineConfig"
            },
            {
              "paramType": "form",
              "name": "LiveSoundText",
              "description": null,
              "conditions": [
                {
                  "field": "Type",
                  "value": "VOICE"
                }
              ],
              "type": "string"
            },
            {
              "paramType": "form",
              "name": "LiveSoundId",
              "description": "ID of Sound to play if call answered by live person",
              "conditions": [
                {
                  "field": "Type",
                  "value": "VOICE"
                }
              ],
              "type": "integer",
              "format": "int64"
            },
            {
              "paramType": "form",
              "name": "LiveSoundTextVoice",
              "description": null,
              "conditions": [
                {
                  "field": "Type",
                  "value": "VOICE"
                }
              ],
              "$ref": "Voice"
            },
            {
              "paramType": "form",
              "name": "MachineSoundText",
              "description": null,
              "conditions": [
                {
                  "field": "Type",
                  "value": "VOICE"
                }
              ],
              "type": "string"
            },
            {
              "paramType": "form",
              "name": "MachineSoundId",
              "description": "ID of Sound to play if call answered by machine",
              "conditions": [
                {
                  "field": "Type",
                  "value": "VOICE"
                }
              ],
              "type": "integer",
              "format": "int64"
            },
            {
              "paramType": "form",
              "name": "MachineSoundTextVoice",
              "description": null,
              "conditions": [
                {
                  "field": "Type",
                  "value": "VOICE"
                }
              ],
              "$ref": "Voice"
            },
            {
              "paramType": "form",
              "name": "TransferSoundText",
              "description": null,
              "conditions": [
                {
                  "field": "Type",
                  "value": "VOICE"
                }
              ],
              "type": "string"
            },
            {
              "paramType": "form",
              "name": "TransferSoundId",
              "description": "ID of Sound to play if call transfered",
              "conditions": [
                {
                  "field": "Type",
                  "value": "VOICE"
                }
              ],
              "type": "integer",
              "format": "int64"
            },
            {
              "paramType": "form",
              "name": "TransferSoundTextVoice",
              "description": null,
              "conditions": [
                {
                  "field": "Type",
                  "value": "VOICE"
                }
              ],
              "$ref": "Voice"
            },
            {
              "paramType": "form",
              "name": "TransferDigit",
              "description": "Phone digit call transfers on if pressed",
              "conditions": [
                {
                  "field": "Type",
                  "value": "VOICE"
                }
              ],
              "$ref": "PhoneDigit"
            },
            {
              "paramType": "form",
              "name": "TransferNumber",
              "description": "Number to transfer call to",
              "conditions": [
                {
                  "field": "Type",
                  "value": "VOICE"
                }
              ],
              "$ref": "PhoneNumber"
            },
            {
              "paramType": "form",
              "name": "DncSoundText",
              "description": null,
